name: ArenaParkour
version: '1.0.0'
main: com.TNTStudios.arenaParkour.ArenaParkour
api-version: '1.18'
authors: [ TNTStudios ]
website: https://tntstudiosn.space/
commands:
  empezar:
    description: Inicia el contador de tiempo.
    permission: op

  detener:
    description: Detiene el contador de tiempo.
    permission: op

  checkpoint:
    description: Guarda un checkpoint.
    permission: op

  regresar:
    description: Regresa al último checkpoint guardado.
    permission: op

